from dutch_parliament.objectives.vote_records import VOTE_RECORDS_OBJECTIVE
from dutch_parliament.objectives.motion_votes import MOTION_VOTES_OBJECTIVE
from dutch_parliament.objectives.motion_content import MOTION_CONTENT_OBJECTIVE
